/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 lighthouse.gltf --transform 
Files: lighthouse.gltf [198.87MB] > lighthouse-transformed.glb [21.48MB] (89%)
Author: Kathrin&Christian (https://sketchfab.com/extracrispi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-lighthouse-323851f10fd7483aa803594767ba693a
Title: Floating Lighthouse
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lighthouse-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_14.geometry} material={materials.ginger} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_23.geometry} material={materials.mushroom_medium_A} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_26.geometry} material={materials.mushroom_small_A} rotation={[-Math.PI / 2, 0, 0]} />
      <lineSegments geometry={nodes.Object_28.geometry} material={materials.mushroom_huge_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.battery} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.book_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.bucket} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.curtain} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.cable} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.book_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.crates} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.flowerpot} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.floors} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.floor} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.frames} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.dome} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.ginger} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.greenhouse_glass} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.greenhouse_metal_inside} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.lamp_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.lamp_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.leaf_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.log_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.log_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.mushroom_medium_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['leaf_B.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.mushroom_small_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.mushroom_huge_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.mushroom_medium_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.mushroom_tiny_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.mushroom_medium_C} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.rock_5} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.stone_C} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.mushroom_small_C} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.platform} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.mushroom_tiny_C} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.sticks_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.sticks_C} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.sticks_D} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.sticks_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.rocks} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.stone_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.stone_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.window} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.wood} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.stone_D} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.stone_stairs} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.artichoke} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.bolts} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.greenhouse_metal} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.klampe} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.lantern_A} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.lantern_B} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.lighthouselamp} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.platform_up} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/lighthouse-transformed.glb')
